### ISSUE TITLE
Set originRequest httpHostHeader for the tunnel

### ISSUE THREAD

**Issue by rafaelreis-r** [ChrispyBacon-dev/DockFlare#102]
Is it possible to have the ability to set this either via ENV or GUI?

```
tunnel: your-tunnel-UUID
credentials-file: /etc/cloudflared/your-tunnel.json

ingress:
  - hostname: service.domain.tld
    service: http://localhost:8000
    originRequest:
      # Force the Host header that reaches Django to be exactly this:
      httpHostHeader: service.domain.tld

      # (Optional) If your upstream is HTTPS, you can disable TLS verify:
      # noTLSVerify: true

  # ... fallback rule
  - service: http_status:404
```
