### ISSUE TITLE
Allow enable Prometheus metrics on managed tunnel container

### ISSUE THREAD

**Issue by luketainton** [ChrispyBacon-dev/DockFlare#107]
Allow a configuration setting that tells DockFlare to enable the Prometheus metrics endpoint on the managed tunnel container (i.e. add the `--metrics IP:PORT` flag).

Example in Docker Compose:
```yaml
services:
  app:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --metrics 0.0.0.0:1234 --no-autoupdate run --token ${TOKEN}
```

This will allow us to collect metrics from the Cloudflare Tunnel that we can visualise in tools such as Grafana.
