### ISSUE TITLE
Muliple ingress rules to the same external host but different paths

### ISSUE THREAD

**Issue by rm-hull** [ChrispyBacon-dev/DockFlare#117]
Say I have two (or more) containers in my docker compose file:

```yaml
  services:
    foo-server:
      ...
      labels:
        - "cloudflare.tunnel.enable=true"
        - "cloudflare.tunnel.hostname=api.my-domain.com"
        - "cloudflare.tunnel.path=/v1/foo"
        - "cloudflare.tunnel.service=http://foo-server:8080"

    bar-server:
      ...
      labels:
        - "cloudflare.tunnel.enable=true"
        - "cloudflare.tunnel.hostname=api.my-domain.com"
        - "cloudflare.tunnel.path=/v1/bar"
        - "cloudflare.tunnel.service=http://bar-server:8080"
```

When this starts up, only one rule is created for the bar-server.. I suspect that either (a) the foo server is created and overwritten, or (b) somewhere in dockflare, it keys config on the hostname only.

I can manually create multiple entries for same endpoint/different path in both dockflare UI and cloudfront UI, so I think this problem is limited to how the automated sweep works

**Comment by ChrispyBacon-dev** [comment]
Yes as mentioned in the documentation currently only one path per sub domain is supported. I can look into that. However this is not a direct issue more a feature request. Can you please repost it into discussion board under ideas? Thank you

**Comment by ChrispyBacon-dev** [comment]
see release notes.
https://github.com/ChrispyBacon-dev/DockFlare/releases/tag/v1.8.9
tested and fully supported. 

let me share you an example how I tested it:
```

version: '3.8'
services:
  nginx-test-paths:
    image: nginx:alpine
    container_name: nginx-path-tester
    restart: unless-stopped
    volumes:
      - ./nginx-test-data/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-test-data/root:/usr/share/nginx/html/root:ro
      - ./nginx-test-data/path1:/usr/share/nginx/html/path1:ro
      - ./nginx-test-data/path2:/usr/share/nginx/html/path2:ro
    networks:
      - cloudflare-net
    labels:
      - "dockflare.enable=true"

      # --- Rule 0: Root path (/) ---
      # This rule handles traffic for the base hostname because it has no 'path' label.
      - "dockflare.0.hostname=nginx-path.mydomain.com"
      - "dockflare.0.service=http://nginx-path-tester:80"
      - "dockflare.0.originsrvname=nginx" # Good practice for SNI

      # --- Rule 1: Specific path /path1 ---
      # All rules for the same hostname must be http/https.
      - "dockflare.1.hostname=nginx-path.mydomain.com"
      - "dockflare.1.path=/path1"
      - "dockflare.1.service=http://nginx-path-tester:80"
      - "dockflare.1.originsrvname=nginx"

      # --- Rule 2: Specific path /path2 ---
      - "dockflare.2.hostname=nginx-path.mydomain.com"
      - "dockflare.2.path=/path2"
      - "dockflare.2.service=http://nginx-path-tester:80"
      - "dockflare.2.originsrvname=nginx"

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true
```

nginx.conf

```
events {}
http {
    server {
        listen 80;
        server_name nginx-path.mydomain.com;

        # Rule for the root path
        location / {
            root /usr/share/nginx/html/root;
            index index.html;
        }

        # Rule for /path1
        location /path1 {
            alias /usr/share/nginx/html/path1;
            index index.html;
        }

        # Rule for /path2
        location /path2 {
            alias /usr/share/nginx/html/path2;
            index index.html;
        }
    }
}
```
