### ISSUE TITLE
Is there a way to set the Cloudflare Tunnel container to use network_mode: host ?

### ISSUE THREAD

**Issue by trentnbauer** [ChrispyBacon-dev/DockFlare#120]
Hi guys!

I would love to use http://localhost:$PORT for my internal address instead of specifying the IP or hostname for each container / compose file! Is it possible to tell DockFlare to create the tunnel with network_mode: host?

Thanks,

**Comment by ChrispyBacon-dev** [comment]
Yes, sure this is working. For example I created a manual rule for an raspberryPi pc in my home network with the local lan ip. Make sure that the docker network is set to external. 

In general I use for my docker containers always the docker name as it is easy to remember and I have some manual rules for external servers/devices that are running outside of the docker server.

There is no need to change to host mode. 

I can post a couple of my compose files as examples.

**Comment by trentnbauer** [comment]
Hi mate,
Would love to see your compose file. I've had a play and no matter what I cannot get the tunnel to run with network_mode: host - only the dockflare container itself, which isn't what I want.

I have tried this,


> ....
>   dockflare:
>     image: alplat/dockflare:v1.8.7@sha256:0c30781a7659ba8f0cdb2f69684aa6cbc4f5ca521a23631a188e226a9eedfe58
>     restart: unless-stopped
>     networks:
>       - cloudflare-net
> ...


> ...
> networks:
>   cloudflare-net:
>     name: cloudflare-net
>     driver: host
> ...


and I get the following error: Failed to deploy a stack: `compose up operation failed: network cloudflare-net was found but has incorrect label com.docker.compose.network set to "" (expected: "cloudflare-net")`

If I delete the cloudflare-net network, I get this error: `Failed to deploy a stack: compose up operation failed: failed to create network cloudflare-net: Error response from daemon: only one instance of "host" network is allowed`

Apologies for all the edits. I understand that only one instance of the "host" networking is allowed and that the appropriate solution would be to use network_mode=host for this, but I cannot figure out how to get this to the tunnel since it is not in the compose file. 

I know there are environmental variables for using an external tunnel container, which would allow me to set network_mode=host for the container in the compose file but it appears I would need to log into the CF portal to get the ID for that tunnel container. My goal here is to never need to log into CF :)

**Comment by ChrispyBacon-dev** [comment]
Sure here a couple of examples. Make sure that the docker network cloudflare-net is created. I have set the docker network to external in order I can connect to services outside of my docker server eg. for home automatation devices/raspberry pi etc. these are manual rules added via DockFlare web. I usually have for every docker container my logging limited so my disks are not getting full of logfiles. Not related to DockFlare but I use Komodo and Github for my stacks and config storage/version control. Don't forget to create a *.tld access policy for authentication. 

dockflare compose:

```
version: '3.8'
services:
  dockflare:
    image: alplat/dockflare:stable
    container_name: dockflare
    restart: unless-stopped
    ports:
      - "5000:5000"  # Web UI port
    labels:
      # -- Cloudflare Tunnel Configuration (via DockFlare) --
      - cloudflare.tunnel.enable=true
      - cloudflare.tunnel.hostname=dockflare.mydomain.com
      - cloudflare.tunnel.service=http://dockflare:5000
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dockflare_data:/app/data
    networks:
      - cloudflare-net 

volumes:
  dockflare_data:

networks:
  cloudflare-net: 
    name: cloudflare-net 
    external: true
```


omada wifi controller:
```
version: "3.8"

services:
  omada-controller:
    image: "mbentley/omada-controller:latest-chromium"
    container_name: "omada-controller"
    hostname: "omada-controller"
    restart: "unless-stopped"

   cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "java"
      - "-server"
      - "-Xms128m"
      - "-Xmx1024m"
      - "-XX:MaxHeapFreeRatio=60"
      - "-XX:MinHeapFreeRatio=30"
      - "-XX:+HeapDumpOnOutOfMemoryError"
      - "-XX:HeapDumpPath=/opt/tplink/EAPController/logs/java_heapdump.hprof"
      - "-Djava.awt.headless=true"
      - "--add-opens"
      - "java.base/sun.security.x509=ALL-UNNAMED"
      - "--add-opens"
      - "java.base/sun.security.util=ALL-UNNAMED"
      - "-cp"
      - "/opt/tplink/EAPController/lib/*::/opt/tplink/EAPController/properties:"
      - "com.tplink.smb.omada.starter.OmadaLinuxMain"
    entrypoint:
      - "/entrypoint.sh"
    working_dir: "/opt/tplink/EAPController/lib"

    environment:
      - "PUID=508"
      - "PGID=508"
      - "TZ=Europe/Berlin" # Ensure this is your correct timezone
      - "MANAGE_HTTPS_PORT=8043"
      - "MANAGE_HTTP_PORT=8088"
      - "PORTAL_HTTP_PORT=8088"
      - "PORTAL_HTTPS_PORT=8843"
      - "PORT_APP_DISCOVERY=27001"
      - "PORT_MANAGER_V1=29811"
      - "PORT_DISCOVERY=29810"
      - "PORT_UPGRADE_V1=29813"
      - "PORT_ADOPT_V1=29812"
      - "PORT_MANAGER_V2=29814"
      - "PORT_TRANSFER_V2=29815"
      - "PORT_RTTY=29816"
      - "SHOW_SERVER_LOGS=true"
      - "SHOW_MONGODB_LOGS=false"
      - "SSL_CERT_NAME=tls.crt"
      - "SSL_KEY_NAME=tls.key"

    ports:
      - "27001:27001/udp"
      - "29810:29810/udp"
      - "8043:8043/tcp"
      - "8088:8088/tcp"
      - "8843:8843/tcp"
      - "29811:29811/tcp"
      - "29812:29812/tcp"
      - "29813:29813/tcp"
      - "29814:29814/tcp"
      - "29815:29815/tcp"
      - "29816:29816/tcp"

    volumes:
      - "omada-data:/opt/tplink/EAPController/data"
      - "omada-logs:/opt/tplink/EAPController/logs"

    networks:
      - "cloudflare-net" # For DockFlare / Cloudflare Tunnel access

    labels:
      "cloudflare.tunnel.enable": "true"
      "cloudflare.tunnel.hostname": "omada.mydomain.com"
      "cloudflare.tunnel.service": "https://omada-controller:8043"
      "cloudflare.tunnel.no_tls_verify": "true" 

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true

volumes:
  omada-data:
    external: true
  omada-logs:
    external: true
```

apprise-api
```
services:
    apprise-api:
      image: lscr.io/linuxserver/apprise-api:latest
      container_name: apprise-api
      hostname: apprise-api
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Zurich
        - APPRISE_ATTACH_SIZE=0 #optional
      volumes:
        - apprise-api:/config
      #  - apprise-api/attachments:/attachments #optional
      ports:
        - 8000:8000
      restart: unless-stopped
      networks:
        - cloudflare-net
      labels:
        # -- Cloudflare Tunnel Configuration (via DockFlare) --
        - cloudflare.tunnel.enable=true
        - cloudflare.tunnel.hostname=apprise.mydomain.com
        - cloudflare.tunnel.service=http://apprise-api:8000
      logging:
        driver: "json-file"
        options:
           max-size: "10m"
           max-file: "2"  
volumes:
  apprise-api:

networks:
  cloudflare-net: 
    name: cloudflare-net 
    external: true      
```

ConvertX Tool

```
services:
  convertx: 
    image: ghcr.io/c4illin/convertx
    container_name: convertx
    restart: unless-stopped
    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
      - "HTTP_ALLOWED=true"
      - "ALLOW_UNAUTHENTICATED=true"
    ports:
      - "3000:3000"
    volumes:
      - /mnt/gdrive/cloud/appdata/convertx/data:/app/data
    networks:
      - "cloudflare-net"
    labels:
      cloudflare.tunnel.enable: "true"
      cloudflare.tunnel.hostname: "convertx.mydomain.com"
      cloudflare.tunnel.service: "http://convertx:3000"                 
        
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

networks:
  cloudflare-net:
    name: cloudflare-net
    external: true
```

change detection

```
services:
    changedetection:
      image: ghcr.io/dgtlmoon/changedetection.io
      container_name: changedetection
      restart: unless-stopped
      hostname: changedetection
      volumes:
        - changedetection-data:/datastore
      environment:
        - PORT=5001
        - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
        - TZ=Europe/Zurich
      labels:
      # -- Cloudflare Tunnel Configuration (via DockFlare) --
        - cloudflare.tunnel.enable=true
        - cloudflare.tunnel.hostname=cd.mydomain.com
        - cloudflare.tunnel.service=http://changedetection:5001
      networks:
        - cloudflare-net 
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "2"
      depends_on:
          browser-sockpuppet-chrome:
              condition: service_started

    browser-sockpuppet-chrome:
      hostname: browser-sockpuppet-chrome
      image: dgtlmoon/sockpuppetbrowser:latest
      cap_add:
        - SYS_ADMIN
      restart: unless-stopped
      networks:
        - cloudflare-net 
      environment:
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1024
        - SCREEN_DEPTH=16
        - MAX_CONCURRENT_CHROME_PROCESSES=10
volumes:
  changedetection-data:

networks:
  cloudflare-net: 
    name: cloudflare-net 
    external: true
```

![Image](https://github.com/user-attachments/assets/09104990-a500-4b3b-9c05-2781571815e7)

**Comment by solipsist01** [comment]
i'm using:

```
    environment:
      - CLOUDFLARED_NETWORK_NAME=somenetwork
```

Could we perhaps add the ability to define more networks there?
I now have attached another network manually to the  dockflare-cloudflared container, which works brilliantly. But logically i think the container will be recreated at some point if it gets updated etc.

**Comment by ChrispyBacon-dev** [comment]
Great suggestion. I'll look into it later.

**Comment by trentnbauer** [comment]
Thanks heaps for sharing your compose files! I have a standard template I use (app for the app, db for databases etc) but have used the hostname variable to work around this, per below

```
version: '3'
services:
  app:
    image: ghcr.io/linuxserver/overseerr:1.34.0@sha256:1205b8873f3ea0a98890191d9e01da911d9509272462a46414ba0378a6d76288
    hostname: ${ALIAS:-overseerr}
    networks:
      - cloudflare-net
    environment:
      - TZ=${TZ:-Australia/Melbourne}
    volumes:
      - app:/config
      #- www:/app/overseerr/public #rebrand overseerr https://github.com/sct/overseerr/issues/404#issuecomment-1659795118
    ports:
      - ${PORT:-5055}:5055
    restart: unless-stopped
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:5055/api/v1/status
      interval: 1m
      timeout: 30s
      retries: 3
      start_period: 30s
    labels:
      - autoheal=true
      - cloudflare.tunnel.enable=true
      - cloudflare.tunnel.hostname=${SUBDOMAIN}.${DOMAIN}
      - cloudflare.tunnel.service=${HTTP:-http://}${ALIAS:-overseerr}:${PORT:-5055}
      - cloudflare.tunnel.access.policy=${CFPOLICY:-default_tld}
      - cloudflare.tunnel.zonename=${DOMAIN}
      - cloudflare.tunnel.path=${URLPATH:-}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"      
volumes:
  app:
  www:

networks:
  cloudflare-net: 
    name: cloudflare-net 
    external: true
```

Edit: I cannot for the life of me work out how to format code blocks correctly
