### ISSUE TITLE
Setup instructions - include adding the containers to the same docker network

### ISSUE THREAD

**Issue by fanteastick** [ChrispyBacon-dev/DockFlare#13]
Thank you for this great project! I was able to get it working perfectly after adding the new containers to the same network as the Dockflare container. I think it'd be helpful if that was mentioned in the setup instructions 😃 

Original:

> Label your Docker containers: To expose services through the Cloudflare Tunnel managed by DockFlare, add labels to your other service containers (e.g., in their docker-compose.yml):

```
services:
  my-web-app:
    image: nginx:latest # Example service
    labels:
      # --- DockFlare Labels ---
      cloudflare.tunnel.enable: "true" # Required: Tells DockFlare to manage this service
      cloudflare.tunnel.hostname: "my-service.example.com" # Required: Your public hostname
      cloudflare.tunnel.service: "http://my-web-app:80" # Required: Internal service URL (use container name/alias and port)
      # cloudflare.tunnel.zonename: "other-domain.com" # Optional: Use if hostname is on a different zone than CF_ZONE_ID
```
Perhaps something like:

> Label your Docker containers and add them to the network: To expose services through the Cloudflare Tunnel managed by DockFlare, add labels to your other service containers (e.g., in their docker-compose.yml)

```
services:
  my-web-app:
    image: nginx:latest # Example service
    labels:
      # --- DockFlare Labels ---
      cloudflare.tunnel.enable: "true" # Required: Tells DockFlare to manage this service
      cloudflare.tunnel.hostname: "my-service.example.com" # Required: Your public hostname
      cloudflare.tunnel.service: "http://my-web-app:80" # Required: Internal service URL (use container name/alias and port)
      # cloudflare.tunnel.zonename: "other-domain.com" # Optional: Use if hostname is on a different zone than CF_ZONE_ID
    networks:
       - cloudflare-net
networks:
  cloudflare-net:
    external: true
    name: cloudflare-net
```

Without adding it to the network, I got errors like this:

- In the cloudflared-agent container: 
> ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp: lookup <SERVICE> on 127.0.0.11:53: server misbehaving" connIndex=0 dest=https://service.example.com/ event=0 ip=<IP ADDR> type=http

- In the dockflare container: 

> [WARNING] Failed to get container <CONTAINER  ID> details after multiple attempts.
> [INFO] Processing stop event for container <CONTAINER  ID>.
> [INFO] Stop event for <CONTAINER  ID>, but it didn't manage an active rule in current state.
